# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//testing/test.gni")

source_set("rhendium_fonts") {
  sources = [
    "rhendium_font_manager.cc",
    "rhendium_font_manager.h",
  ]

  deps = [
    "//base",
    "//crypto",
    "//skia",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "rhendium_font_manager_unittest.cc" ]
  deps = [
    ":rhendium_fonts",
    "//base",
    "//base/test:test_support",
    "//crypto",
    "//skia",
    "//testing/gtest",
  ]
  data_deps = [ "//third_party/test_fonts" ]
}

test("rhendium_font_manager_unittests") {
  deps = [
    ":unit_tests",
    "//testing/gtest:gtest_main",
  ]
}
